FROM timbru31/java-node:slim

WORKDIR /app
ENV NODE_ENV development
ENV JNI_PATH /usr/lib/jvm/java-8-openjdk-amd64/include
COPY package.json .
RUN yarn install --production

RUN apt-get update && \
    apt-get install -y g++ make && \
    apt-get install -y openjdk-8-jdk

COPY . .
RUN (cd ./Agora_Recording_SDK_for_Linux_FULL/samples/java/; ./build.sh build)
RUN cp ./Agora_Recording_SDK_for_Linux_FULL/samples/cpp/recorder_local ./
RUN cp ./Agora_Recording_SDK_for_Linux_FULL/bin ./
RUN rm -rf Agora_Recording_SDK_for_Linux_FULL

CMD ["yarn", "start"]

EXPOSE 8080
