version: '3'
services:
  mongo:
    image: mongo:4.1
  web:
    build: 
      context: .
      dockerfile: DockerFile
    ports:
     - "8080:8080"
    environment:
     - MONGODB_URI=mongodb://mongo:27017/AgoraDB 
    links:
     - mongo 
    depends_on: 
     - mongo 
    volumes:
     - .:/app
     - /app/node_modules
